# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0166790ccf7da5fd4fe70c8767469b07edbaf8814a1e3c5ebf5cd1a16a14480193d4ac4d4f8293aba39e37c0ceca8a1ccae7bbc5bfb2c5a31d7980737779ab35

test:
  secret_key_base: 75c17d26e1cf86a4d2d15621aea77fde66fa024d9a12e76c15486aaa37a18cf9eca07524f2f270acb89af350b53c37689dc1f905e3f7869cb1b8d55a819bec6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
